### ISSUE TITLE
Forward to telegram channel

### ISSUE THREAD

**Issue by suntong** [LeKovr/teleproxy#1]
Apart from "_forwards them to telegram group_", it isn't hard to forwards them to telegram channel right? 
I.e., can we use the code as-is to do that, or the code need to be enhanced to do that? Thx.

**Comment by LeKovr** [comment]
Group is used for receiving operator commads, so `Type: "group"` is hardcoded [here](https://github.com/LeKovr/teleproxy/blob/master/cmd/teleproxy/app.go#L152)
I guess this name can be moved to config for support [other types](https://godoc.org/gopkg.in/tucnak/telebot.v2#ChatType)

So, code needs to be enhanced

**Comment by suntong** [comment]
after the 3rd push in https://github.com/LeKovr/teleproxy/pull/10, forwarding to telegram channel works just as fine, though not through `make` but through directly calling `./teleproxy --log_level debug --group $GROUP --token $TOKEN --template $TEMPLATE --command ./commands.sh` in terminal. Don't know why, but it works.

**Comment by suntong** [comment]
![image](https://user-images.githubusercontent.com/422244/40954547-037a1c34-6853-11e8-97ab-1483642014cc.png)
