### ISSUE TITLE
Allowing flags to be defined in environment variables

### ISSUE THREAD

**Issue by suntong** [LeKovr/teleproxy#2]
is it a good idea to allow flags to be defined in environment variables as well? 

Like, https://github.com/go-easygen/easygen#-easygen, 

> Flag defaults can be overridden by corresponding environment variable

and https://github.com/go-easygen/easygen#easygen-itself

> there are three tiers program parameters can be given:
> 
> Default values defined within the program, so that program parameters can have meaningful 
> 
> 1. defaults to start with
> 1. Values defined in environment variables
> 1. Values passed from command line
> 
> The latter will have higher priority and will override values defined formerly. I.e., the values from command line will override that in environment variables, which in turn override program defaults.

If you agree, I don't mind sending a PR to make the changes.

**Comment by suntong** [comment]
give up.

**Comment by LeKovr** [comment]
We use github.com/jessevdk/go-flags which allows flags to be defined in environment variables, but did not check yet is it working. Could you check?

**Comment by suntong** [comment]
Ref #3, the bottleneck is the CLI interface, thus replacing it.
