### ISSUE TITLE
undefined: Asset

### ISSUE THREAD

**Issue by suntong** [LeKovr/teleproxy#5]
when I tried to build it, I get:

     ./app.go:137:11: undefined: Asset

how can I fix it? Thx.

**Comment by LeKovr** [comment]
You should run `go generate ./cmd/teleproxy/...`, see also `gen` target in Makefile

**Comment by suntong** [comment]
Fixed. ref: https://github.com/kubernetes/minikube/issues/1735
Oh, thanks for the reply.
